
# Ngon ngu cua mach muon kiem tra testbench
TOPLEVEL_LANG = verilog

# Source file (file nguon muon chay testbench)
VERILOG_SOURCES = mux_8to1_16bit.v

# module chinh trong source file
TOPLEVEL = mux_8to1_16bit

# file name cua testbench
MODULE = mux_8to1_16bit_tb

# designate app mo phong
SIM = icarus

# bien dich file
include $(shell cocotb-config --makefiles)/Makefile.sim
