/* Generated by Yosys 0.48+5 (git sha1 4581f75b0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "mux_8to1_16bit.v:4.1-65.10" *)
module mux_8to1_16bit(r0, r1, r2, r3, r4, r5, r6, r7, aluout, din, gout, rout, din_enable, buswires);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "mux_8to1_16bit.v:16.17-16.23" *)
  input [15:0] aluout;
  wire [15:0] aluout;
  (* src = "mux_8to1_16bit.v:30.23-30.31" *)
  output [15:0] buswires;
  wire [15:0] buswires;
  (* src = "mux_8to1_16bit.v:18.17-18.20" *)
  input [15:0] din;
  wire [15:0] din;
  (* src = "mux_8to1_16bit.v:27.11-27.21" *)
  input din_enable;
  wire din_enable;
  (* src = "mux_8to1_16bit.v:25.11-25.15" *)
  input gout;
  wire gout;
  (* src = "mux_8to1_16bit.v:7.17-7.19" *)
  input [15:0] r0;
  wire [15:0] r0;
  (* src = "mux_8to1_16bit.v:8.17-8.19" *)
  input [15:0] r1;
  wire [15:0] r1;
  (* src = "mux_8to1_16bit.v:9.17-9.19" *)
  input [15:0] r2;
  wire [15:0] r2;
  (* src = "mux_8to1_16bit.v:10.17-10.19" *)
  input [15:0] r3;
  wire [15:0] r3;
  (* src = "mux_8to1_16bit.v:11.17-11.19" *)
  input [15:0] r4;
  wire [15:0] r4;
  (* src = "mux_8to1_16bit.v:12.17-12.19" *)
  input [15:0] r5;
  wire [15:0] r5;
  (* src = "mux_8to1_16bit.v:13.17-13.19" *)
  input [15:0] r6;
  wire [15:0] r6;
  (* src = "mux_8to1_16bit.v:14.17-14.19" *)
  input [15:0] r7;
  wire [15:0] r7;
  (* src = "mux_8to1_16bit.v:26.17-26.21" *)
  input [2:0] rout;
  wire [2:0] rout;
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(aluout[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(aluout[1]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(aluout[2]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(aluout[3]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _140_ (
    .A(aluout[4]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _141_ (
    .A(aluout[5]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _142_ (
    .A(aluout[6]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _143_ (
    .A(aluout[7]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _144_ (
    .A(aluout[8]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(aluout[9]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _146_ (
    .A(aluout[10]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _147_ (
    .A(aluout[11]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(aluout[12]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _149_ (
    .A(aluout[13]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _150_ (
    .A(aluout[14]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and3_1 _151_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .X(_015_)
  );
  sky130_fd_sc_hd__and3b_1 _152_ (
    .A_N(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .X(_016_)
  );
  sky130_fd_sc_hd__nor3b_1 _153_ (
    .A(rout[1]),
    .B(rout[0]),
    .C_N(rout[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor4b_1 _155_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[0]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__and3b_1 _156_ (
    .A_N(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor3b_1 _157_ (
    .A(rout[2]),
    .B(rout[1]),
    .C_N(rout[0]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor3b_1 _158_ (
    .A(rout[2]),
    .B(rout[0]),
    .C_N(rout[1]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__and3b_1 _159_ (
    .A_N(rout[1]),
    .B(rout[0]),
    .C(rout[2]),
    .X(_023_)
  );
  sky130_fd_sc_hd__a22oi_1 _160_ (
    .A1(r7[0]),
    .A2(_015_),
    .B1(_023_),
    .B2(r5[0]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a221oi_1 _161_ (
    .A1(r4[0]),
    .A2(_017_),
    .B1(_021_),
    .B2(r1[0]),
    .C1(_019_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a22oi_1 _162_ (
    .A1(r3[0]),
    .A2(_020_),
    .B1(_022_),
    .B2(r2[0]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _163_ (
    .A1(r6[0]),
    .A2(_016_),
    .B1(gout),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand4_1 _164_ (
    .A(_024_),
    .B(_025_),
    .C(_026_),
    .D(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21oi_1 _165_ (
    .A1(_000_),
    .A2(gout),
    .B1(din_enable),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a22o_1 _166_ (
    .A1(din[0]),
    .A2(din_enable),
    .B1(_028_),
    .B2(_029_),
    .X(buswires[0])
  );
  sky130_fd_sc_hd__a21oi_1 _167_ (
    .A1(r4[1]),
    .A2(_017_),
    .B1(gout),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor4b_1 _168_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[1]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a221oi_1 _169_ (
    .A1(r6[1]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[1]),
    .C1(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a22oi_1 _170_ (
    .A1(r2[1]),
    .A2(_022_),
    .B1(_023_),
    .B2(r5[1]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a22oi_1 _171_ (
    .A1(r7[1]),
    .A2(_015_),
    .B1(_021_),
    .B2(r1[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand4_1 _172_ (
    .A(_030_),
    .B(_032_),
    .C(_033_),
    .D(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _173_ (
    .A1(gout),
    .A2(_001_),
    .B1(din_enable),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a22o_1 _174_ (
    .A1(din_enable),
    .A2(din[1]),
    .B1(_035_),
    .B2(_036_),
    .X(buswires[1])
  );
  sky130_fd_sc_hd__nor4bb_1 _175_ (
    .A(rout[2]),
    .B(rout[1]),
    .C_N(rout[0]),
    .D_N(r1[2]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a22oi_1 _176_ (
    .A1(r4[2]),
    .A2(_017_),
    .B1(_018_),
    .B2(r0[2]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a221oi_1 _177_ (
    .A1(r3[2]),
    .A2(_020_),
    .B1(_022_),
    .B2(r2[2]),
    .C1(_037_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a22oi_1 _178_ (
    .A1(r6[2]),
    .A2(_016_),
    .B1(_023_),
    .B2(r5[2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _179_ (
    .A1(r7[2]),
    .A2(_015_),
    .B1(gout),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand4_1 _180_ (
    .A(_038_),
    .B(_039_),
    .C(_040_),
    .D(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _181_ (
    .A1(gout),
    .A2(_002_),
    .B1(din_enable),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a22o_1 _182_ (
    .A1(din_enable),
    .A2(din[2]),
    .B1(_042_),
    .B2(_043_),
    .X(buswires[2])
  );
  sky130_fd_sc_hd__and4b_1 _183_ (
    .A_N(rout[1]),
    .B(rout[0]),
    .C(r5[3]),
    .D(rout[2]),
    .X(_044_)
  );
  sky130_fd_sc_hd__a22oi_1 _184_ (
    .A1(r7[3]),
    .A2(_015_),
    .B1(_022_),
    .B2(r2[3]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a221oi_1 _185_ (
    .A1(r6[3]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[3]),
    .C1(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a22oi_1 _186_ (
    .A1(r0[3]),
    .A2(_018_),
    .B1(_021_),
    .B2(r1[3]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _187_ (
    .A1(r4[3]),
    .A2(_017_),
    .B1(gout),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand4_1 _188_ (
    .A(_045_),
    .B(_046_),
    .C(_047_),
    .D(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _189_ (
    .A1(gout),
    .A2(_003_),
    .B1(din_enable),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a22o_1 _190_ (
    .A1(din_enable),
    .A2(din[3]),
    .B1(_049_),
    .B2(_050_),
    .X(buswires[3])
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(r4[4]),
    .A2(_017_),
    .B1(gout),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor4b_1 _192_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[4]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a221oi_1 _193_ (
    .A1(r3[4]),
    .A2(_020_),
    .B1(_022_),
    .B2(r2[4]),
    .C1(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a22oi_1 _194_ (
    .A1(r6[4]),
    .A2(_016_),
    .B1(_023_),
    .B2(r5[4]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a22oi_1 _195_ (
    .A1(r7[4]),
    .A2(_015_),
    .B1(_021_),
    .B2(r1[4]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand4_1 _196_ (
    .A(_051_),
    .B(_053_),
    .C(_054_),
    .D(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a21oi_1 _197_ (
    .A1(gout),
    .A2(_004_),
    .B1(din_enable),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a22o_1 _198_ (
    .A1(din_enable),
    .A2(din[4]),
    .B1(_056_),
    .B2(_057_),
    .X(buswires[4])
  );
  sky130_fd_sc_hd__a21oi_1 _199_ (
    .A1(r5[5]),
    .A2(_023_),
    .B1(gout),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor4b_1 _200_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[5]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a221oi_1 _201_ (
    .A1(r6[5]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[5]),
    .C1(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a22oi_1 _202_ (
    .A1(r4[5]),
    .A2(_017_),
    .B1(_022_),
    .B2(r2[5]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a22oi_1 _203_ (
    .A1(r7[5]),
    .A2(_015_),
    .B1(_021_),
    .B2(r1[5]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand4_1 _204_ (
    .A(_058_),
    .B(_060_),
    .C(_061_),
    .D(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _205_ (
    .A1(gout),
    .A2(_005_),
    .B1(din_enable),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22o_1 _206_ (
    .A1(din_enable),
    .A2(din[5]),
    .B1(_063_),
    .B2(_064_),
    .X(buswires[5])
  );
  sky130_fd_sc_hd__nor4bb_1 _207_ (
    .A(rout[2]),
    .B(rout[1]),
    .C_N(rout[0]),
    .D_N(r1[6]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a22oi_1 _208_ (
    .A1(r0[6]),
    .A2(_018_),
    .B1(_023_),
    .B2(r5[6]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a221oi_1 _209_ (
    .A1(r6[6]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[6]),
    .C1(_065_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a22oi_1 _210_ (
    .A1(r4[6]),
    .A2(_017_),
    .B1(_022_),
    .B2(r2[6]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a21oi_1 _211_ (
    .A1(r7[6]),
    .A2(_015_),
    .B1(gout),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand4_1 _212_ (
    .A(_066_),
    .B(_067_),
    .C(_068_),
    .D(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a21oi_1 _213_ (
    .A1(gout),
    .A2(_006_),
    .B1(din_enable),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a22o_1 _214_ (
    .A1(din_enable),
    .A2(din[6]),
    .B1(_070_),
    .B2(_071_),
    .X(buswires[6])
  );
  sky130_fd_sc_hd__and4b_1 _215_ (
    .A_N(rout[1]),
    .B(rout[0]),
    .C(r5[7]),
    .D(rout[2]),
    .X(_072_)
  );
  sky130_fd_sc_hd__a22oi_1 _216_ (
    .A1(r0[7]),
    .A2(_018_),
    .B1(_021_),
    .B2(r1[7]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a221oi_1 _217_ (
    .A1(r6[7]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[7]),
    .C1(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a22oi_1 _218_ (
    .A1(r7[7]),
    .A2(_015_),
    .B1(_017_),
    .B2(r4[7]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _219_ (
    .A1(r2[7]),
    .A2(_022_),
    .B1(gout),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand4_1 _220_ (
    .A(_073_),
    .B(_074_),
    .C(_075_),
    .D(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a21oi_1 _221_ (
    .A1(gout),
    .A2(_007_),
    .B1(din_enable),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a22o_1 _222_ (
    .A1(din_enable),
    .A2(din[7]),
    .B1(_077_),
    .B2(_078_),
    .X(buswires[7])
  );
  sky130_fd_sc_hd__a21oi_1 _223_ (
    .A1(r4[8]),
    .A2(_017_),
    .B1(gout),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor4b_1 _224_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[8]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a221oi_1 _225_ (
    .A1(r3[8]),
    .A2(_020_),
    .B1(_022_),
    .B2(r2[8]),
    .C1(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a22oi_1 _226_ (
    .A1(r6[8]),
    .A2(_016_),
    .B1(_023_),
    .B2(r5[8]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a22oi_1 _227_ (
    .A1(r7[8]),
    .A2(_015_),
    .B1(_021_),
    .B2(r1[8]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand4_1 _228_ (
    .A(_079_),
    .B(_081_),
    .C(_082_),
    .D(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a21oi_1 _229_ (
    .A1(gout),
    .A2(_008_),
    .B1(din_enable),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a22o_1 _230_ (
    .A1(din_enable),
    .A2(din[8]),
    .B1(_084_),
    .B2(_085_),
    .X(buswires[8])
  );
  sky130_fd_sc_hd__nor4bb_1 _231_ (
    .A(rout[2]),
    .B(rout[1]),
    .C_N(rout[0]),
    .D_N(r1[9]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a22oi_1 _232_ (
    .A1(r0[9]),
    .A2(_018_),
    .B1(_023_),
    .B2(r5[9]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a221oi_1 _233_ (
    .A1(r6[9]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[9]),
    .C1(_086_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a22oi_1 _234_ (
    .A1(r4[9]),
    .A2(_017_),
    .B1(_022_),
    .B2(r2[9]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a21oi_1 _235_ (
    .A1(r7[9]),
    .A2(_015_),
    .B1(gout),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand4_1 _236_ (
    .A(_087_),
    .B(_088_),
    .C(_089_),
    .D(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _237_ (
    .A1(gout),
    .A2(_009_),
    .B1(din_enable),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a22o_1 _238_ (
    .A1(din_enable),
    .A2(din[9]),
    .B1(_091_),
    .B2(_092_),
    .X(buswires[9])
  );
  sky130_fd_sc_hd__and4b_1 _239_ (
    .A_N(rout[1]),
    .B(rout[0]),
    .C(r5[10]),
    .D(rout[2]),
    .X(_093_)
  );
  sky130_fd_sc_hd__a22oi_1 _240_ (
    .A1(r0[10]),
    .A2(_018_),
    .B1(_021_),
    .B2(r1[10]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a221oi_1 _241_ (
    .A1(r6[10]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[10]),
    .C1(_093_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a22oi_1 _242_ (
    .A1(r7[10]),
    .A2(_015_),
    .B1(_017_),
    .B2(r4[10]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_1 _243_ (
    .A1(r2[10]),
    .A2(_022_),
    .B1(gout),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand4_1 _244_ (
    .A(_094_),
    .B(_095_),
    .C(_096_),
    .D(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a21oi_1 _245_ (
    .A1(gout),
    .A2(_010_),
    .B1(din_enable),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a22o_1 _246_ (
    .A1(din_enable),
    .A2(din[10]),
    .B1(_098_),
    .B2(_099_),
    .X(buswires[10])
  );
  sky130_fd_sc_hd__nor4bb_1 _247_ (
    .A(rout[1]),
    .B(rout[0]),
    .C_N(r4[11]),
    .D_N(rout[2]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a22oi_1 _248_ (
    .A1(r7[11]),
    .A2(_015_),
    .B1(_022_),
    .B2(r2[11]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a221oi_1 _249_ (
    .A1(r6[11]),
    .A2(_016_),
    .B1(_021_),
    .B2(r1[11]),
    .C1(_100_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a22oi_1 _250_ (
    .A1(r0[11]),
    .A2(_018_),
    .B1(_020_),
    .B2(r3[11]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a21oi_1 _251_ (
    .A1(r5[11]),
    .A2(_023_),
    .B1(gout),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _252_ (
    .A(_101_),
    .B(_102_),
    .C(_103_),
    .D(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _253_ (
    .A1(gout),
    .A2(_011_),
    .B1(din_enable),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a22o_1 _254_ (
    .A1(din_enable),
    .A2(din[11]),
    .B1(_105_),
    .B2(_106_),
    .X(buswires[11])
  );
  sky130_fd_sc_hd__nor4bb_1 _255_ (
    .A(rout[1]),
    .B(rout[0]),
    .C_N(r4[12]),
    .D_N(rout[2]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a22oi_1 _256_ (
    .A1(r7[12]),
    .A2(_015_),
    .B1(_022_),
    .B2(r2[12]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a221oi_1 _257_ (
    .A1(r6[12]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[12]),
    .C1(_107_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a22oi_1 _258_ (
    .A1(r0[12]),
    .A2(_018_),
    .B1(_021_),
    .B2(r1[12]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21oi_1 _259_ (
    .A1(r5[12]),
    .A2(_023_),
    .B1(gout),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand4_1 _260_ (
    .A(_108_),
    .B(_109_),
    .C(_110_),
    .D(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _261_ (
    .A1(gout),
    .A2(_012_),
    .B1(din_enable),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a22o_1 _262_ (
    .A1(din_enable),
    .A2(din[12]),
    .B1(_112_),
    .B2(_113_),
    .X(buswires[12])
  );
  sky130_fd_sc_hd__and4b_1 _263_ (
    .A_N(rout[1]),
    .B(rout[0]),
    .C(r5[13]),
    .D(rout[2]),
    .X(_114_)
  );
  sky130_fd_sc_hd__a22oi_1 _264_ (
    .A1(r7[13]),
    .A2(_015_),
    .B1(_022_),
    .B2(r2[13]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a221oi_1 _265_ (
    .A1(r6[13]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[13]),
    .C1(_114_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a22oi_1 _266_ (
    .A1(r0[13]),
    .A2(_018_),
    .B1(_021_),
    .B2(r1[13]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21oi_1 _267_ (
    .A1(r4[13]),
    .A2(_017_),
    .B1(gout),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand4_1 _268_ (
    .A(_115_),
    .B(_116_),
    .C(_117_),
    .D(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _269_ (
    .A1(gout),
    .A2(_013_),
    .B1(din_enable),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a22o_1 _270_ (
    .A1(din_enable),
    .A2(din[13]),
    .B1(_119_),
    .B2(_120_),
    .X(buswires[13])
  );
  sky130_fd_sc_hd__nor4b_1 _271_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[14]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22oi_1 _272_ (
    .A1(r4[14]),
    .A2(_017_),
    .B1(_022_),
    .B2(r2[14]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a221oi_1 _273_ (
    .A1(r6[14]),
    .A2(_016_),
    .B1(_020_),
    .B2(r3[14]),
    .C1(_121_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a22oi_1 _274_ (
    .A1(r7[14]),
    .A2(_015_),
    .B1(_021_),
    .B2(r1[14]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(r5[14]),
    .A2(_023_),
    .B1(gout),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand4_1 _276_ (
    .A(_122_),
    .B(_123_),
    .C(_124_),
    .D(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(gout),
    .A2(_014_),
    .B1(din_enable),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a22o_1 _278_ (
    .A1(din_enable),
    .A2(din[14]),
    .B1(_126_),
    .B2(_127_),
    .X(buswires[14])
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(din_enable),
    .B(din[15]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor4b_1 _280_ (
    .A(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .D_N(r0[15]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a22o_1 _281_ (
    .A1(r4[15]),
    .A2(_017_),
    .B1(_021_),
    .B2(r1[15]),
    .X(_130_)
  );
  sky130_fd_sc_hd__a221o_1 _282_ (
    .A1(r3[15]),
    .A2(_020_),
    .B1(_022_),
    .B2(r2[15]),
    .C1(_129_),
    .X(_131_)
  );
  sky130_fd_sc_hd__a22o_1 _283_ (
    .A1(r6[15]),
    .A2(_016_),
    .B1(_023_),
    .B2(r5[15]),
    .X(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(r7[15]),
    .A2(_015_),
    .B1(gout),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor4b_1 _285_ (
    .A(_130_),
    .B(_131_),
    .C(_132_),
    .D_N(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _286_ (
    .A(gout),
    .SLEEP(aluout[15]),
    .X(_135_)
  );
  sky130_fd_sc_hd__o31ai_1 _287_ (
    .A1(din_enable),
    .A2(_134_),
    .A3(_135_),
    .B1(_128_),
    .Y(buswires[15])
  );
endmodule
