/* Generated by Yosys 0.48+5 (git sha1 4581f75b0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "ALU_16bit.v:28.1-73.10" *)
module ALU_16bit(clk, buswires, ain, gin, sub, aluout);
  (* src = "ALU_16bit.v:33.11-33.14" *)
  input ain;
  wire ain;
  (* src = "ALU_16bit.v:37.19-37.25" *)
  output [15:0] aluout;
  wire [15:0] aluout;
  (* src = "ALU_16bit.v:30.18-30.26" *)
  input [15:0] buswires;
  wire [15:0] buswires;
  (* src = "ALU_16bit.v:29.11-29.14" *)
  input clk;
  wire clk;
  (* src = "ALU_16bit.v:34.11-34.14" *)
  input gin;
  wire gin;
  (* src = "ALU_16bit.v:39.17-39.22" *)
  wire [15:0] raout;
  (* src = "ALU_16bit.v:39.24-39.30" *)
  wire [15:0] result;
  (* src = "ALU_16bit.v:35.11-35.14" *)
  input sub;
  wire sub;
  (* module_not_derived = 32'd1 *)
  (* src = "ALU_16bit.v:52.12-57.6" *)
  AddSub addsub (
    .buswires_A(buswires),
    .raout(raout),
    .result(result),
    .sub(sub)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ALU_16bit.v:43.20-48.10" *)
  register_16bit reg_a (
    .Rout(raout),
    .buswires(buswires),
    .clk(clk),
    .rin(ain)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ALU_16bit.v:61.20-66.10" *)
  register_16bit reg_g (
    .Rout(aluout),
    .buswires(result),
    .clk(clk),
    .rin(gin)
  );
endmodule

(* src = "ALU_16bit.v:7.1-23.10" *)
module AddSub(buswires_A, raout, sub, result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  (* src = "ALU_16bit.v:8.18-8.28" *)
  input [15:0] buswires_A;
  wire [15:0] buswires_A;
  (* src = "ALU_16bit.v:16.10-16.18" *)
  wire carry_in;
  (* src = "ALU_16bit.v:9.18-9.23" *)
  input [15:0] raout;
  wire [15:0] raout;
  (* src = "ALU_16bit.v:13.19-13.25" *)
  output [15:0] result;
  wire [15:0] result;
  (* src = "ALU_16bit.v:12.11-12.14" *)
  input sub;
  wire sub;
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(raout[0]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _084_ (
    .A(buswires_A[0]),
    .B(sub),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _085_ (
    .A(raout[0]),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _086_ (
    .A(raout[0]),
    .SLEEP(_040_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _087_ (
    .A(sub),
    .B(_041_),
    .C(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _088_ (
    .A(sub),
    .B(buswires_A[1]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _089_ (
    .A(raout[1]),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor3_1 _090_ (
    .A(sub),
    .B(buswires_A[1]),
    .C(raout[1]),
    .X(_046_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _091_ (
    .A(_043_),
    .SLEEP(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__or3b_1 _092_ (
    .A(_039_),
    .B(_046_),
    .C_N(_040_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(_041_),
    .B(_046_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21boi_0 _095_ (
    .A1(_043_),
    .A2(_050_),
    .B1_N(_047_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__xor2_1 _096_ (
    .A(sub),
    .B(buswires_A[2]),
    .X(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(raout[2]),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _098_ (
    .A1(_045_),
    .A2(_048_),
    .B1(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_1 _099_ (
    .A(_045_),
    .B(_048_),
    .C(_052_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2b_1 _100_ (
    .A_N(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _101_ (
    .A(_047_),
    .SLEEP(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xor2_1 _102_ (
    .A(_047_),
    .B(_055_),
    .X(result[2])
  );
  sky130_fd_sc_hd__a21oi_1 _103_ (
    .A1(raout[2]),
    .A2(_051_),
    .B1(_053_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _104_ (
    .A(sub),
    .B(buswires_A[3]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _105_ (
    .A(raout[3]),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _106_ (
    .A(raout[3]),
    .B(_058_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xor2_1 _107_ (
    .A(_057_),
    .B(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2b_1 _108_ (
    .A(_056_),
    .B_N(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(_056_),
    .B(_061_),
    .Y(result[3])
  );
  sky130_fd_sc_hd__o21ai_0 _110_ (
    .A1(_057_),
    .A2(_060_),
    .B1(_059_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _111_ (
    .A(sub),
    .B(buswires_A[4]),
    .X(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _112_ (
    .A(raout[4]),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(_062_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xor2_1 _115_ (
    .A(_062_),
    .B(_066_),
    .X(result[4])
  );
  sky130_fd_sc_hd__maj3_1 _116_ (
    .A(raout[4]),
    .B(_063_),
    .C(_064_),
    .X(_068_)
  );
  sky130_fd_sc_hd__xor2_1 _117_ (
    .A(sub),
    .B(buswires_A[5]),
    .X(_069_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(raout[5]),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xor2_1 _119_ (
    .A(_068_),
    .B(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _120_ (
    .A(_067_),
    .SLEEP(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__xor2_1 _121_ (
    .A(_067_),
    .B(_071_),
    .X(result[5])
  );
  sky130_fd_sc_hd__maj3_1 _122_ (
    .A(raout[5]),
    .B(_068_),
    .C(_069_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xor2_1 _123_ (
    .A(sub),
    .B(buswires_A[6]),
    .X(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _124_ (
    .A(raout[6]),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _125_ (
    .A(_073_),
    .B(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _126_ (
    .A(_072_),
    .SLEEP(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__xor2_1 _127_ (
    .A(_072_),
    .B(_076_),
    .X(result[6])
  );
  sky130_fd_sc_hd__maj3_1 _128_ (
    .A(raout[6]),
    .B(_073_),
    .C(_074_),
    .X(_078_)
  );
  sky130_fd_sc_hd__xor2_1 _129_ (
    .A(sub),
    .B(buswires_A[7]),
    .X(_079_)
  );
  sky130_fd_sc_hd__xnor2_1 _130_ (
    .A(raout[7]),
    .B(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xor2_1 _131_ (
    .A(_078_),
    .B(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _132_ (
    .A(_077_),
    .SLEEP(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _133_ (
    .A(_077_),
    .B(_081_),
    .X(result[7])
  );
  sky130_fd_sc_hd__maj3_1 _134_ (
    .A(raout[7]),
    .B(_078_),
    .C(_079_),
    .X(_000_)
  );
  sky130_fd_sc_hd__xor2_1 _135_ (
    .A(sub),
    .B(buswires_A[8]),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _136_ (
    .A(raout[8]),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_1 _137_ (
    .A(_000_),
    .B(_002_),
    .X(_003_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _138_ (
    .A(_082_),
    .SLEEP(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _139_ (
    .A(_082_),
    .B(_003_),
    .X(result[8])
  );
  sky130_fd_sc_hd__maj3_1 _140_ (
    .A(raout[8]),
    .B(_000_),
    .C(_001_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xor2_1 _141_ (
    .A(sub),
    .B(buswires_A[9]),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _142_ (
    .A(raout[9]),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xor2_1 _143_ (
    .A(_005_),
    .B(_007_),
    .X(_008_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _144_ (
    .A(_004_),
    .SLEEP(_008_),
    .X(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _145_ (
    .A(_004_),
    .B(_008_),
    .X(result[9])
  );
  sky130_fd_sc_hd__maj3_1 _146_ (
    .A(raout[9]),
    .B(_005_),
    .C(_006_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _147_ (
    .A(sub),
    .B(buswires_A[10]),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _148_ (
    .A(raout[10]),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _149_ (
    .A(_010_),
    .B(_012_),
    .X(_013_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _150_ (
    .A(_009_),
    .SLEEP(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__xor2_1 _151_ (
    .A(_009_),
    .B(_013_),
    .X(result[10])
  );
  sky130_fd_sc_hd__maj3_1 _152_ (
    .A(raout[10]),
    .B(_010_),
    .C(_011_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _153_ (
    .A(sub),
    .B(buswires_A[11]),
    .X(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(raout[11]),
    .B(_016_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xor2_1 _155_ (
    .A(_015_),
    .B(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _156_ (
    .A(_014_),
    .SLEEP(_018_),
    .X(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _157_ (
    .A(_014_),
    .B(_018_),
    .X(result[11])
  );
  sky130_fd_sc_hd__maj3_1 _158_ (
    .A(raout[11]),
    .B(_015_),
    .C(_016_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xor2_1 _159_ (
    .A(sub),
    .B(buswires_A[12]),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _160_ (
    .A(raout[12]),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _161_ (
    .A(_020_),
    .B(_022_),
    .X(_023_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _162_ (
    .A(_019_),
    .SLEEP(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _163_ (
    .A(_019_),
    .B(_023_),
    .X(result[12])
  );
  sky130_fd_sc_hd__maj3_1 _164_ (
    .A(raout[12]),
    .B(_020_),
    .C(_021_),
    .X(_025_)
  );
  sky130_fd_sc_hd__xor2_1 _165_ (
    .A(sub),
    .B(buswires_A[13]),
    .X(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _166_ (
    .A(raout[13]),
    .B(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _167_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(_024_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _169_ (
    .A(_024_),
    .B(_028_),
    .X(result[13])
  );
  sky130_fd_sc_hd__maj3_1 _170_ (
    .A(raout[13]),
    .B(_025_),
    .C(_026_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xor2_1 _171_ (
    .A(sub),
    .B(buswires_A[14]),
    .X(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _172_ (
    .A(raout[14]),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _173_ (
    .A(_030_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _175_ (
    .A(_029_),
    .B(_033_),
    .X(result[14])
  );
  sky130_fd_sc_hd__maj3_1 _176_ (
    .A(raout[14]),
    .B(_030_),
    .C(_031_),
    .X(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _177_ (
    .A(buswires_A[15]),
    .B(raout[15]),
    .X(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(sub),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _179_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(_034_),
    .B(_038_),
    .Y(result[15])
  );
  sky130_fd_sc_hd__xor2_1 _181_ (
    .A(buswires_A[0]),
    .B(raout[0]),
    .X(result[0])
  );
  assign carry_in = sub;
endmodule

(* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:3.1-25.10" *)
module register_16bit(clk, rin, buswires, Rout);
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:10.23-10.27" *)
  output [15:0] Rout;
  wire [15:0] Rout;
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:8.18-8.26" *)
  input [15:0] buswires;
  wire [15:0] buswires;
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:6.11-6.14" *)
  input rin;
  wire rin;
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _00_ (
    .CLK(clk),
    .D(buswires[12]),
    .DE(rin),
    .Q(Rout[12])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _01_ (
    .CLK(clk),
    .D(buswires[13]),
    .DE(rin),
    .Q(Rout[13])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _02_ (
    .CLK(clk),
    .D(buswires[14]),
    .DE(rin),
    .Q(Rout[14])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _03_ (
    .CLK(clk),
    .D(buswires[15]),
    .DE(rin),
    .Q(Rout[15])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _04_ (
    .CLK(clk),
    .D(buswires[0]),
    .DE(rin),
    .Q(Rout[0])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _05_ (
    .CLK(clk),
    .D(buswires[1]),
    .DE(rin),
    .Q(Rout[1])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _06_ (
    .CLK(clk),
    .D(buswires[2]),
    .DE(rin),
    .Q(Rout[2])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _07_ (
    .CLK(clk),
    .D(buswires[3]),
    .DE(rin),
    .Q(Rout[3])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _08_ (
    .CLK(clk),
    .D(buswires[4]),
    .DE(rin),
    .Q(Rout[4])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _09_ (
    .CLK(clk),
    .D(buswires[5]),
    .DE(rin),
    .Q(Rout[5])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _10_ (
    .CLK(clk),
    .D(buswires[6]),
    .DE(rin),
    .Q(Rout[6])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _11_ (
    .CLK(clk),
    .D(buswires[7]),
    .DE(rin),
    .Q(Rout[7])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _12_ (
    .CLK(clk),
    .D(buswires[8]),
    .DE(rin),
    .Q(Rout[8])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _13_ (
    .CLK(clk),
    .D(buswires[9]),
    .DE(rin),
    .Q(Rout[9])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _14_ (
    .CLK(clk),
    .D(buswires[10]),
    .DE(rin),
    .Q(Rout[10])
  );
  (* src = "/home/hong/Workplace/Verilog/Verification_files/reg_16bit/register_16bit.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _15_ (
    .CLK(clk),
    .D(buswires[11]),
    .DE(rin),
    .Q(Rout[11])
  );
endmodule
