/* Generated by Yosys 0.48+5 (git sha1 4581f75b0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* src = "CPU.v:332.1-373.10" *)
module ALU_16bit(clk, buswires, ain, gin, sub, aluout);
  (* src = "CPU.v:337.11-337.14" *)
  input ain;
  wire ain;
  (* src = "CPU.v:341.19-341.25" *)
  output [15:0] aluout;
  wire [15:0] aluout;
  (* src = "CPU.v:334.18-334.26" *)
  input [15:0] buswires;
  wire [15:0] buswires;
  (* src = "CPU.v:333.11-333.14" *)
  input clk;
  wire clk;
  (* src = "CPU.v:338.11-338.14" *)
  input gin;
  wire gin;
  (* src = "CPU.v:343.17-343.22" *)
  wire [15:0] raout;
  (* src = "CPU.v:343.24-343.30" *)
  wire [15:0] result;
  (* src = "CPU.v:339.11-339.14" *)
  input sub;
  wire sub;
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:356.12-361.6" *)
  AddSub addsub (
    .buswires_A(buswires),
    .raout(raout),
    .result(result),
    .sub(sub)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:347.20-352.10" *)
  register_16bit reg_a (
    .Rout(raout),
    .buswires(buswires),
    .clk(clk),
    .rin(ain)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:365.20-370.10" *)
  register_16bit reg_g (
    .Rout(aluout),
    .buswires(result),
    .clk(clk),
    .rin(gin)
  );
endmodule

(* src = "CPU.v:312.1-328.10" *)
module AddSub(buswires_A, raout, sub, result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  (* src = "CPU.v:313.18-313.28" *)
  input [15:0] buswires_A;
  wire [15:0] buswires_A;
  (* src = "CPU.v:321.10-321.18" *)
  wire carry_in;
  (* src = "CPU.v:314.18-314.23" *)
  input [15:0] raout;
  wire [15:0] raout;
  (* src = "CPU.v:318.19-318.25" *)
  output [15:0] result;
  wire [15:0] result;
  (* src = "CPU.v:317.11-317.14" *)
  input sub;
  wire sub;
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(raout[0]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _084_ (
    .A(buswires_A[0]),
    .B(sub),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _085_ (
    .A(raout[0]),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _086_ (
    .A(raout[0]),
    .SLEEP(_040_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _087_ (
    .A(sub),
    .B(_041_),
    .C(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _088_ (
    .A(sub),
    .B(buswires_A[1]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _089_ (
    .A(raout[1]),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor3_1 _090_ (
    .A(sub),
    .B(buswires_A[1]),
    .C(raout[1]),
    .X(_046_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _091_ (
    .A(_043_),
    .SLEEP(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__or3b_1 _092_ (
    .A(_039_),
    .B(_046_),
    .C_N(_040_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(_041_),
    .B(_046_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21boi_0 _095_ (
    .A1(_043_),
    .A2(_050_),
    .B1_N(_047_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__xor2_1 _096_ (
    .A(sub),
    .B(buswires_A[2]),
    .X(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(raout[2]),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _098_ (
    .A1(_045_),
    .A2(_048_),
    .B1(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand3_1 _099_ (
    .A(_045_),
    .B(_048_),
    .C(_052_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2b_1 _100_ (
    .A_N(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _101_ (
    .A(_047_),
    .SLEEP(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xor2_1 _102_ (
    .A(_047_),
    .B(_055_),
    .X(result[2])
  );
  sky130_fd_sc_hd__a21oi_1 _103_ (
    .A1(raout[2]),
    .A2(_051_),
    .B1(_053_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xor2_1 _104_ (
    .A(sub),
    .B(buswires_A[3]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _105_ (
    .A(raout[3]),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _106_ (
    .A(raout[3]),
    .B(_058_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xor2_1 _107_ (
    .A(_057_),
    .B(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2b_1 _108_ (
    .A(_056_),
    .B_N(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(_056_),
    .B(_061_),
    .Y(result[3])
  );
  sky130_fd_sc_hd__o21ai_0 _110_ (
    .A1(_057_),
    .A2(_060_),
    .B1(_059_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _111_ (
    .A(sub),
    .B(buswires_A[4]),
    .X(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _112_ (
    .A(raout[4]),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(_062_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xor2_1 _115_ (
    .A(_062_),
    .B(_066_),
    .X(result[4])
  );
  sky130_fd_sc_hd__maj3_1 _116_ (
    .A(raout[4]),
    .B(_063_),
    .C(_064_),
    .X(_068_)
  );
  sky130_fd_sc_hd__xor2_1 _117_ (
    .A(sub),
    .B(buswires_A[5]),
    .X(_069_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(raout[5]),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xor2_1 _119_ (
    .A(_068_),
    .B(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _120_ (
    .A(_067_),
    .SLEEP(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__xor2_1 _121_ (
    .A(_067_),
    .B(_071_),
    .X(result[5])
  );
  sky130_fd_sc_hd__maj3_1 _122_ (
    .A(raout[5]),
    .B(_068_),
    .C(_069_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xor2_1 _123_ (
    .A(sub),
    .B(buswires_A[6]),
    .X(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _124_ (
    .A(raout[6]),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _125_ (
    .A(_073_),
    .B(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _126_ (
    .A(_072_),
    .SLEEP(_076_),
    .X(_077_)
  );
  sky130_fd_sc_hd__xor2_1 _127_ (
    .A(_072_),
    .B(_076_),
    .X(result[6])
  );
  sky130_fd_sc_hd__maj3_1 _128_ (
    .A(raout[6]),
    .B(_073_),
    .C(_074_),
    .X(_078_)
  );
  sky130_fd_sc_hd__xor2_1 _129_ (
    .A(sub),
    .B(buswires_A[7]),
    .X(_079_)
  );
  sky130_fd_sc_hd__xnor2_1 _130_ (
    .A(raout[7]),
    .B(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xor2_1 _131_ (
    .A(_078_),
    .B(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _132_ (
    .A(_077_),
    .SLEEP(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _133_ (
    .A(_077_),
    .B(_081_),
    .X(result[7])
  );
  sky130_fd_sc_hd__maj3_1 _134_ (
    .A(raout[7]),
    .B(_078_),
    .C(_079_),
    .X(_000_)
  );
  sky130_fd_sc_hd__xor2_1 _135_ (
    .A(sub),
    .B(buswires_A[8]),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _136_ (
    .A(raout[8]),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_1 _137_ (
    .A(_000_),
    .B(_002_),
    .X(_003_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _138_ (
    .A(_082_),
    .SLEEP(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _139_ (
    .A(_082_),
    .B(_003_),
    .X(result[8])
  );
  sky130_fd_sc_hd__maj3_1 _140_ (
    .A(raout[8]),
    .B(_000_),
    .C(_001_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xor2_1 _141_ (
    .A(sub),
    .B(buswires_A[9]),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _142_ (
    .A(raout[9]),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xor2_1 _143_ (
    .A(_005_),
    .B(_007_),
    .X(_008_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _144_ (
    .A(_004_),
    .SLEEP(_008_),
    .X(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _145_ (
    .A(_004_),
    .B(_008_),
    .X(result[9])
  );
  sky130_fd_sc_hd__maj3_1 _146_ (
    .A(raout[9]),
    .B(_005_),
    .C(_006_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _147_ (
    .A(sub),
    .B(buswires_A[10]),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _148_ (
    .A(raout[10]),
    .B(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _149_ (
    .A(_010_),
    .B(_012_),
    .X(_013_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _150_ (
    .A(_009_),
    .SLEEP(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__xor2_1 _151_ (
    .A(_009_),
    .B(_013_),
    .X(result[10])
  );
  sky130_fd_sc_hd__maj3_1 _152_ (
    .A(raout[10]),
    .B(_010_),
    .C(_011_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _153_ (
    .A(sub),
    .B(buswires_A[11]),
    .X(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(raout[11]),
    .B(_016_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xor2_1 _155_ (
    .A(_015_),
    .B(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _156_ (
    .A(_014_),
    .SLEEP(_018_),
    .X(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _157_ (
    .A(_014_),
    .B(_018_),
    .X(result[11])
  );
  sky130_fd_sc_hd__maj3_1 _158_ (
    .A(raout[11]),
    .B(_015_),
    .C(_016_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xor2_1 _159_ (
    .A(sub),
    .B(buswires_A[12]),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _160_ (
    .A(raout[12]),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _161_ (
    .A(_020_),
    .B(_022_),
    .X(_023_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _162_ (
    .A(_019_),
    .SLEEP(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _163_ (
    .A(_019_),
    .B(_023_),
    .X(result[12])
  );
  sky130_fd_sc_hd__maj3_1 _164_ (
    .A(raout[12]),
    .B(_020_),
    .C(_021_),
    .X(_025_)
  );
  sky130_fd_sc_hd__xor2_1 _165_ (
    .A(sub),
    .B(buswires_A[13]),
    .X(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _166_ (
    .A(raout[13]),
    .B(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _167_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(_024_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _169_ (
    .A(_024_),
    .B(_028_),
    .X(result[13])
  );
  sky130_fd_sc_hd__maj3_1 _170_ (
    .A(raout[13]),
    .B(_025_),
    .C(_026_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xor2_1 _171_ (
    .A(sub),
    .B(buswires_A[14]),
    .X(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _172_ (
    .A(raout[14]),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _173_ (
    .A(_030_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _175_ (
    .A(_029_),
    .B(_033_),
    .X(result[14])
  );
  sky130_fd_sc_hd__maj3_1 _176_ (
    .A(raout[14]),
    .B(_030_),
    .C(_031_),
    .X(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _177_ (
    .A(buswires_A[15]),
    .B(raout[15]),
    .X(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(sub),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xnor2_1 _179_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(_034_),
    .B(_038_),
    .Y(result[15])
  );
  sky130_fd_sc_hd__xor2_1 _181_ (
    .A(buswires_A[0]),
    .B(raout[0]),
    .X(result[0])
  );
  assign carry_in = sub;
endmodule

(* top =  1  *)
(* src = "CPU.v:377.1-543.10" *)
module CPU_16bit(run, resetn, clk, din, buswires, done);
  (* src = "CPU.v:414.12-414.14" *)
  wire [8:0] IR;
  (* src = "CPU.v:413.6-413.10" *)
  wire IRin;
  (* src = "CPU.v:403.6-403.9" *)
  wire ain;
  (* src = "CPU.v:406.13-406.19" *)
  wire [15:0] aluout;
  (* src = "CPU.v:383.19-383.27" *)
  output [15:0] buswires;
  wire [15:0] buswires;
  (* src = "CPU.v:417.6-417.11" *)
  wire clear;
  (* src = "CPU.v:380.11-380.14" *)
  input clk;
  wire clk;
  (* src = "CPU.v:381.18-381.21" *)
  input [15:0] din;
  wire [15:0] din;
  (* src = "CPU.v:390.6-390.20" *)
  wire din_enable_CPU;
  (* src = "CPU.v:384.12-384.16" *)
  output done;
  wire done;
  (* src = "CPU.v:405.6-405.9" *)
  wire gin;
  (* src = "CPU.v:391.6-391.10" *)
  wire gout;
  (* src = "CPU.v:392.13-392.15" *)
  wire [15:0] r0;
  (* src = "CPU.v:393.13-393.15" *)
  wire [15:0] r1;
  (* src = "CPU.v:394.13-394.15" *)
  wire [15:0] r2;
  (* src = "CPU.v:395.13-395.15" *)
  wire [15:0] r3;
  (* src = "CPU.v:396.13-396.15" *)
  wire [15:0] r4;
  (* src = "CPU.v:397.13-397.15" *)
  wire [15:0] r5;
  (* src = "CPU.v:398.13-398.15" *)
  wire [15:0] r6;
  (* src = "CPU.v:399.13-399.15" *)
  wire [15:0] r7;
  (* src = "CPU.v:379.11-379.17" *)
  input resetn;
  wire resetn;
  (* src = "CPU.v:409.11-409.14" *)
  wire [7:0] rin;
  (* src = "CPU.v:389.12-389.16" *)
  wire [2:0] rout;
  (* src = "CPU.v:378.11-378.14" *)
  input run;
  wire run;
  (* src = "CPU.v:418.12-418.17" *)
  wire [1:0] state;
  (* src = "CPU.v:404.6-404.9" *)
  wire sub;
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:420.11-427.2" *)
  ALU_16bit ALU_16bit (
    .ain(ain),
    .aluout(aluout),
    .buswires(buswires),
    .clk(clk),
    .gin(gin),
    .sub(sub)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:517.14-532.2" *)
  Control_Unit Control_unit_module (
    .IR(IR),
    .IRin(IRin),
    .ain(ain),
    .clear(clear),
    .din_enable(din_enable_CPU),
    .done(done),
    .gin(gin),
    .gout(gout),
    .resetn(resetn),
    .rin(rin),
    .rout(rout),
    .run(run),
    .state(state),
    .sub(sub)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:436.16-451.2" *)
  mux_8to1_16bit Mux (
    .aluout(aluout),
    .buswires(buswires),
    .din(din),
    .din_enable(din_enable_CPU),
    .gout(gout),
    .r0(r0),
    .r1(r1),
    .r2(r2),
    .r3(r3),
    .r4(r4),
    .r5(r5),
    .r6(r6),
    .r7(r7),
    .rout(rout)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:511.9-515.2" *)
  PC_2bit counter_2bit (
    .clk(clk),
    .clr(clear),
    .state(state)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:429.4-434.2" *)
  IR intr_reg (
    .IR_in(IRin),
    .IR_out(IR),
    .clk(clk),
    .din(din)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:454.16-459.2" *)
  register_16bit register0 (
    .Rout(r0),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:461.16-466.2" *)
  register_16bit register1 (
    .Rout(r1),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:468.16-473.2" *)
  register_16bit register2 (
    .Rout(r2),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:475.16-480.2" *)
  register_16bit register3 (
    .Rout(r3),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:482.16-487.2" *)
  register_16bit register4 (
    .Rout(r4),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:489.16-494.2" *)
  register_16bit register5 (
    .Rout(r5),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:496.16-501.2" *)
  register_16bit register6 (
    .Rout(r6),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "CPU.v:503.16-508.2" *)
  register_16bit register7 (
    .Rout(r7),
    .buswires(buswires),
    .clk(clk),
    .rin(rin[7])
  );
endmodule

(* src = "CPU.v:124.1-310.10" *)
module Control_Unit(run, resetn, IR, state, IRin, rin, rout, din_enable, gout, ain, gin, sub, clear, done);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "CPU.v:128.16-128.18" *)
  input [8:0] IR;
  wire [8:0] IR;
  (* src = "CPU.v:132.12-132.16" *)
  output IRin;
  wire IRin;
  (* src = "CPU.v:147.5-147.12" *)
  wire IRin_CU;
  (* src = "CPU.v:140.16-140.19" *)
  output ain;
  wire ain;
  (* src = "CPU.v:144.12-144.17" *)
  output clear;
  wire clear;
  (* src = "CPU.v:151.5-151.13" *)
  wire clear_CU;
  (* src = "CPU.v:137.12-137.22" *)
  output din_enable;
  wire din_enable;
  (* src = "CPU.v:149.5-149.18" *)
  wire din_enable_CU;
  (* src = "CPU.v:145.12-145.16" *)
  output done;
  wire done;
  (* src = "CPU.v:152.5-152.12" *)
  wire done_CU;
  (* src = "CPU.v:141.16-141.19" *)
  output gin;
  wire gin;
  (* src = "CPU.v:138.12-138.16" *)
  output gout;
  wire gout;
  (* src = "CPU.v:150.5-150.12" *)
  wire gout_CU;
  (* src = "CPU.v:163.12-163.18" *)
  wire [2:0] opcode;
  (* src = "CPU.v:127.11-127.17" *)
  input resetn;
  wire resetn;
  (* src = "CPU.v:134.18-134.21" *)
  output [7:0] rin;
  wire [7:0] rin;
  (* src = "CPU.v:148.11-148.17" *)
  wire [7:0] rin_CU;
  (* nosync = 32'd1 *)
  (* src = "CPU.v:296.35-296.37" *)
  wire [2:0] \rin_mux$func$CPU.v:223$6.rx ;
  (* nosync = 32'd1 *)
  (* src = "CPU.v:296.35-296.37" *)
  wire [2:0] \rin_mux$func$CPU.v:232$7.rx ;
  (* nosync = 32'd1 *)
  (* src = "CPU.v:296.35-296.37" *)
  wire [2:0] \rin_mux$func$CPU.v:240$8.rx ;
  (* nosync = 32'd1 *)
  (* src = "CPU.v:296.35-296.37" *)
  wire [2:0] \rin_mux$func$CPU.v:275$9.rx ;
  (* src = "CPU.v:136.21-136.25" *)
  output [2:0] rout;
  wire [2:0] rout;
  (* src = "CPU.v:126.11-126.14" *)
  input run;
  wire run;
  (* src = "CPU.v:164.12-164.14" *)
  wire [2:0] rx;
  (* src = "CPU.v:165.12-165.14" *)
  wire [2:0] ry;
  (* src = "CPU.v:129.16-129.21" *)
  input [1:0] state;
  wire [1:0] state;
  (* src = "CPU.v:142.16-142.19" *)
  output sub;
  wire sub;
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(state[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(run),
    .B(resetn),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _26_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2b_1 _27_ (
    .A_N(IR[8]),
    .B(IR[7]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _28_ (
    .A1(state[1]),
    .A2(_03_),
    .B1(state[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand3_1 _29_ (
    .A(run),
    .B(resetn),
    .C(_04_),
    .Y(clear)
  );
  sky130_fd_sc_hd__nor2_1 _30_ (
    .A(_01_),
    .B(_04_),
    .Y(done)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(_01_),
    .B(_02_),
    .Y(gout)
  );
  sky130_fd_sc_hd__nand2b_1 _32_ (
    .A_N(state[1]),
    .B(state[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _33_ (
    .A(IR[7]),
    .B(IR[8]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand2_1 _34_ (
    .A(IR[6]),
    .B(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor3_1 _35_ (
    .A(_01_),
    .B(_05_),
    .C(_07_),
    .Y(din_enable)
  );
  sky130_fd_sc_hd__o21ai_0 _36_ (
    .A1(_00_),
    .A2(IR[8]),
    .B1(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _37_ (
    .A(IR[5]),
    .B(_01_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _38_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3_1 _39_ (
    .A(IR[3]),
    .B(IR[4]),
    .C(_10_),
    .Y(rin[0])
  );
  sky130_fd_sc_hd__nand2b_1 _40_ (
    .A_N(IR[4]),
    .B(IR[3]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _41_ (
    .A(_10_),
    .B(_11_),
    .Y(rin[1])
  );
  sky130_fd_sc_hd__nand2b_1 _42_ (
    .A_N(IR[3]),
    .B(IR[4]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _43_ (
    .A(_10_),
    .B(_12_),
    .Y(rin[2])
  );
  sky130_fd_sc_hd__nand2_1 _44_ (
    .A(IR[3]),
    .B(IR[4]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _45_ (
    .A(_10_),
    .B(_13_),
    .Y(rin[3])
  );
  sky130_fd_sc_hd__nand4_1 _46_ (
    .A(run),
    .B(resetn),
    .C(IR[5]),
    .D(_08_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _47_ (
    .A(IR[3]),
    .B(IR[4]),
    .C(_14_),
    .Y(rin[4])
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(_11_),
    .B(_14_),
    .Y(rin[5])
  );
  sky130_fd_sc_hd__nor2_1 _49_ (
    .A(_12_),
    .B(_14_),
    .Y(rin[6])
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(_13_),
    .B(_14_),
    .Y(rin[7])
  );
  sky130_fd_sc_hd__nor3_1 _51_ (
    .A(state[1]),
    .B(state[0]),
    .C(_01_),
    .Y(IRin)
  );
  sky130_fd_sc_hd__nand3b_1 _52_ (
    .A_N(IR[8]),
    .B(IR[7]),
    .C(state[1]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor3_1 _53_ (
    .A(state[0]),
    .B(_01_),
    .C(_15_),
    .Y(gin)
  );
  sky130_fd_sc_hd__and2_0 _54_ (
    .A(IR[6]),
    .B(gin),
    .X(sub)
  );
  sky130_fd_sc_hd__nor3_1 _55_ (
    .A(_01_),
    .B(_03_),
    .C(_05_),
    .Y(ain)
  );
  sky130_fd_sc_hd__nor2_1 _56_ (
    .A(IR[7]),
    .B(IR[6]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__and2_0 _57_ (
    .A(_02_),
    .B(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _58_ (
    .A(_02_),
    .B(_16_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__or3_1 _59_ (
    .A(IR[7]),
    .B(IR[6]),
    .C(IR[8]),
    .X(_19_)
  );
  sky130_fd_sc_hd__o22ai_1 _60_ (
    .A1(state[0]),
    .A2(_15_),
    .B1(_19_),
    .B2(_05_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a32oi_1 _61_ (
    .A1(IR[3]),
    .A2(_08_),
    .A3(_18_),
    .B1(_20_),
    .B2(IR[0]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor2_1 _62_ (
    .A(_01_),
    .B(_21_),
    .Y(rout[0])
  );
  sky130_fd_sc_hd__a32oi_1 _63_ (
    .A1(IR[4]),
    .A2(_08_),
    .A3(_18_),
    .B1(_20_),
    .B2(IR[1]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _64_ (
    .A(_01_),
    .B(_22_),
    .Y(rout[1])
  );
  sky130_fd_sc_hd__nand4_1 _65_ (
    .A(IR[2]),
    .B(run),
    .C(resetn),
    .D(_20_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o21ai_0 _66_ (
    .A1(_14_),
    .A2(_17_),
    .B1(_23_),
    .Y(rout[2])
  );
  assign IRin_CU = IRin;
  assign clear_CU = clear;
  assign din_enable_CU = din_enable;
  assign done_CU = done;
  assign gout_CU = gout;
  assign opcode = IR[8:6];
  assign rin_CU = rin;
  assign \rin_mux$func$CPU.v:223$6.rx  = 3'hx;
  assign \rin_mux$func$CPU.v:232$7.rx  = 3'hx;
  assign \rin_mux$func$CPU.v:240$8.rx  = 3'hx;
  assign \rin_mux$func$CPU.v:275$9.rx  = 3'hx;
  assign rx = IR[5:3];
  assign ry = IR[2:0];
endmodule

(* src = "CPU.v:106.1-121.10" *)
module IR(din, IR_in, clk, IR_out);
  (* src = "CPU.v:108.11-108.16" *)
  input IR_in;
  wire IR_in;
  (* src = "CPU.v:110.22-110.28" *)
  output [8:0] IR_out;
  wire [8:0] IR_out;
  (* src = "CPU.v:109.11-109.14" *)
  input clk;
  wire clk;
  (* src = "CPU.v:107.18-107.21" *)
  input [15:0] din;
  wire [15:0] din;
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _0_ (
    .CLK(clk),
    .D(din[0]),
    .DE(IR_in),
    .Q(IR_out[0])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _1_ (
    .CLK(clk),
    .D(din[1]),
    .DE(IR_in),
    .Q(IR_out[1])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _2_ (
    .CLK(clk),
    .D(din[2]),
    .DE(IR_in),
    .Q(IR_out[2])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _3_ (
    .CLK(clk),
    .D(din[3]),
    .DE(IR_in),
    .Q(IR_out[3])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _4_ (
    .CLK(clk),
    .D(din[4]),
    .DE(IR_in),
    .Q(IR_out[4])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _5_ (
    .CLK(clk),
    .D(din[5]),
    .DE(IR_in),
    .Q(IR_out[5])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _6_ (
    .CLK(clk),
    .D(din[6]),
    .DE(IR_in),
    .Q(IR_out[6])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _7_ (
    .CLK(clk),
    .D(din[7]),
    .DE(IR_in),
    .Q(IR_out[7])
  );
  (* src = "CPU.v:112.5-120.8" *)
  sky130_fd_sc_hd__edfxtp_1 _8_ (
    .CLK(clk),
    .D(din[8]),
    .DE(IR_in),
    .Q(IR_out[8])
  );
endmodule

(* src = "CPU.v:26.1-42.10" *)
module PC_2bit(clk, clr, state);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "CPU.v:27.11-27.14" *)
  input clk;
  wire clk;
  (* src = "CPU.v:28.11-28.14" *)
  input clr;
  wire clr;
  (* src = "CPU.v:29.22-29.27" *)
  output [1:0] state;
  wire [1:0] state;
  sky130_fd_sc_hd__nor2_1 _3_ (
    .A(clr),
    .B(state[0]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__xnor2_1 _4_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_2_)
  );
  sky130_fd_sc_hd__nor2_1 _5_ (
    .A(clr),
    .B(_2_),
    .Y(_1_)
  );
  (* src = "CPU.v:32.5-40.8" *)
  sky130_fd_sc_hd__dfxtp_1 _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(state[0])
  );
  (* src = "CPU.v:32.5-40.8" *)
  sky130_fd_sc_hd__dfxtp_1 _7_ (
    .CLK(clk),
    .D(_1_),
    .Q(state[1])
  );
endmodule

(* src = "CPU.v:44.1-103.10" *)
module mux_8to1_16bit(r0, r1, r2, r3, r4, r5, r6, r7, aluout, din, gout, rout, din_enable, buswires);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "CPU.v:56.17-56.23" *)
  input [15:0] aluout;
  wire [15:0] aluout;
  (* src = "CPU.v:70.24-70.32" *)
  output [15:0] buswires;
  wire [15:0] buswires;
  (* src = "CPU.v:73.12-73.24" *)
  wire [15:0] buswires_reg;
  (* src = "CPU.v:58.17-58.20" *)
  input [15:0] din;
  wire [15:0] din;
  (* src = "CPU.v:67.11-67.21" *)
  input din_enable;
  wire din_enable;
  (* src = "CPU.v:65.11-65.15" *)
  input gout;
  wire gout;
  (* src = "CPU.v:47.17-47.19" *)
  input [15:0] r0;
  wire [15:0] r0;
  (* src = "CPU.v:48.17-48.19" *)
  input [15:0] r1;
  wire [15:0] r1;
  (* src = "CPU.v:49.17-49.19" *)
  input [15:0] r2;
  wire [15:0] r2;
  (* src = "CPU.v:50.17-50.19" *)
  input [15:0] r3;
  wire [15:0] r3;
  (* src = "CPU.v:51.17-51.19" *)
  input [15:0] r4;
  wire [15:0] r4;
  (* src = "CPU.v:52.17-52.19" *)
  input [15:0] r5;
  wire [15:0] r5;
  (* src = "CPU.v:53.17-53.19" *)
  input [15:0] r6;
  wire [15:0] r6;
  (* src = "CPU.v:54.17-54.19" *)
  input [15:0] r7;
  wire [15:0] r7;
  (* src = "CPU.v:66.17-66.21" *)
  input [2:0] rout;
  wire [2:0] rout;
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(aluout[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(aluout[1]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(aluout[2]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(aluout[3]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _140_ (
    .A(aluout[4]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _141_ (
    .A(aluout[5]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _142_ (
    .A(aluout[6]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _143_ (
    .A(aluout[7]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _144_ (
    .A(aluout[8]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _145_ (
    .A(aluout[9]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _146_ (
    .A(aluout[10]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _147_ (
    .A(aluout[11]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(aluout[12]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _149_ (
    .A(aluout[13]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _150_ (
    .A(aluout[14]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(aluout[15]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__and3_1 _152_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .X(_016_)
  );
  sky130_fd_sc_hd__and3b_1 _153_ (
    .A_N(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .X(_017_)
  );
  sky130_fd_sc_hd__and3b_1 _154_ (
    .A_N(rout[1]),
    .B(rout[2]),
    .C(rout[0]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nor3b_1 _155_ (
    .A(rout[1]),
    .B(rout[2]),
    .C_N(rout[0]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__and3b_1 _156_ (
    .A_N(rout[2]),
    .B(rout[1]),
    .C(rout[0]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor3_1 _157_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor4b_1 _158_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[0]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3b_1 _159_ (
    .A(rout[0]),
    .B(rout[2]),
    .C_N(rout[1]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor3b_1 _160_ (
    .A(rout[0]),
    .B(rout[1]),
    .C_N(rout[2]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a22oi_1 _161_ (
    .A1(r7[0]),
    .A2(_016_),
    .B1(_024_),
    .B2(r4[0]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a221oi_1 _162_ (
    .A1(r5[0]),
    .A2(_018_),
    .B1(_019_),
    .B2(r1[0]),
    .C1(_022_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a22oi_1 _163_ (
    .A1(r3[0]),
    .A2(_020_),
    .B1(_023_),
    .B2(r2[0]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _164_ (
    .A1(r6[0]),
    .A2(_017_),
    .B1(gout),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand4_1 _165_ (
    .A(_025_),
    .B(_026_),
    .C(_027_),
    .D(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _166_ (
    .A1(_000_),
    .A2(gout),
    .B1(din_enable),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a22o_1 _167_ (
    .A1(din[0]),
    .A2(din_enable),
    .B1(_029_),
    .B2(_030_),
    .X(buswires[0])
  );
  sky130_fd_sc_hd__a21oi_1 _168_ (
    .A1(r4[1]),
    .A2(_024_),
    .B1(gout),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor4b_1 _169_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[1]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a221oi_1 _170_ (
    .A1(r3[1]),
    .A2(_020_),
    .B1(_023_),
    .B2(r2[1]),
    .C1(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a22oi_1 _171_ (
    .A1(r6[1]),
    .A2(_017_),
    .B1(_018_),
    .B2(r5[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a22oi_1 _172_ (
    .A1(r7[1]),
    .A2(_016_),
    .B1(_019_),
    .B2(r1[1]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand4_1 _173_ (
    .A(_031_),
    .B(_033_),
    .C(_034_),
    .D(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _174_ (
    .A1(gout),
    .A2(_001_),
    .B1(din_enable),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a22o_1 _175_ (
    .A1(din_enable),
    .A2(din[1]),
    .B1(_036_),
    .B2(_037_),
    .X(buswires[1])
  );
  sky130_fd_sc_hd__nor4bb_1 _176_ (
    .A(rout[0]),
    .B(rout[1]),
    .C_N(rout[2]),
    .D_N(r4[2]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a22oi_1 _177_ (
    .A1(r1[2]),
    .A2(_019_),
    .B1(_021_),
    .B2(r0[2]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a221oi_1 _178_ (
    .A1(r6[2]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[2]),
    .C1(_038_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a22oi_1 _179_ (
    .A1(r7[2]),
    .A2(_016_),
    .B1(_018_),
    .B2(r5[2]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _180_ (
    .A1(r2[2]),
    .A2(_023_),
    .B1(gout),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand4_1 _181_ (
    .A(_039_),
    .B(_040_),
    .C(_041_),
    .D(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _182_ (
    .A1(gout),
    .A2(_002_),
    .B1(din_enable),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a22o_1 _183_ (
    .A1(din_enable),
    .A2(din[2]),
    .B1(_043_),
    .B2(_044_),
    .X(buswires[2])
  );
  sky130_fd_sc_hd__nor4b_1 _184_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[3]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a22oi_1 _185_ (
    .A1(r2[3]),
    .A2(_023_),
    .B1(_024_),
    .B2(r4[3]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a221oi_1 _186_ (
    .A1(r6[3]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[3]),
    .C1(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a22oi_1 _187_ (
    .A1(r7[3]),
    .A2(_016_),
    .B1(_019_),
    .B2(r1[3]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _188_ (
    .A1(r5[3]),
    .A2(_018_),
    .B1(gout),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand4_1 _189_ (
    .A(_046_),
    .B(_047_),
    .C(_048_),
    .D(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _190_ (
    .A1(gout),
    .A2(_003_),
    .B1(din_enable),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a22o_1 _191_ (
    .A1(din_enable),
    .A2(din[3]),
    .B1(_050_),
    .B2(_051_),
    .X(buswires[3])
  );
  sky130_fd_sc_hd__a21oi_1 _192_ (
    .A1(r4[4]),
    .A2(_024_),
    .B1(gout),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor4b_1 _193_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[4]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a221oi_1 _194_ (
    .A1(r3[4]),
    .A2(_020_),
    .B1(_023_),
    .B2(r2[4]),
    .C1(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a22oi_1 _195_ (
    .A1(r6[4]),
    .A2(_017_),
    .B1(_018_),
    .B2(r5[4]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a22oi_1 _196_ (
    .A1(r7[4]),
    .A2(_016_),
    .B1(_019_),
    .B2(r1[4]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand4_1 _197_ (
    .A(_052_),
    .B(_054_),
    .C(_055_),
    .D(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a21oi_1 _198_ (
    .A1(gout),
    .A2(_004_),
    .B1(din_enable),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a22o_1 _199_ (
    .A1(din_enable),
    .A2(din[4]),
    .B1(_057_),
    .B2(_058_),
    .X(buswires[4])
  );
  sky130_fd_sc_hd__and4b_1 _200_ (
    .A_N(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D(r6[5]),
    .X(_059_)
  );
  sky130_fd_sc_hd__a21oi_1 _201_ (
    .A1(r2[5]),
    .A2(_023_),
    .B1(gout),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a221oi_1 _202_ (
    .A1(r1[5]),
    .A2(_019_),
    .B1(_024_),
    .B2(r4[5]),
    .C1(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a22oi_1 _203_ (
    .A1(r3[5]),
    .A2(_020_),
    .B1(_021_),
    .B2(r0[5]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a22oi_1 _204_ (
    .A1(r7[5]),
    .A2(_016_),
    .B1(_018_),
    .B2(r5[5]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand4_1 _205_ (
    .A(_060_),
    .B(_061_),
    .C(_062_),
    .D(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a21oi_1 _206_ (
    .A1(gout),
    .A2(_005_),
    .B1(din_enable),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a22o_1 _207_ (
    .A1(din_enable),
    .A2(din[5]),
    .B1(_064_),
    .B2(_065_),
    .X(buswires[5])
  );
  sky130_fd_sc_hd__and4b_1 _208_ (
    .A_N(rout[1]),
    .B(rout[2]),
    .C(r5[6]),
    .D(rout[0]),
    .X(_066_)
  );
  sky130_fd_sc_hd__a22oi_1 _209_ (
    .A1(r7[6]),
    .A2(_016_),
    .B1(_023_),
    .B2(r2[6]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a221oi_1 _210_ (
    .A1(r6[6]),
    .A2(_017_),
    .B1(_019_),
    .B2(r1[6]),
    .C1(_066_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a22oi_1 _211_ (
    .A1(r3[6]),
    .A2(_020_),
    .B1(_021_),
    .B2(r0[6]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a21oi_1 _212_ (
    .A1(r4[6]),
    .A2(_024_),
    .B1(gout),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand4_1 _213_ (
    .A(_067_),
    .B(_068_),
    .C(_069_),
    .D(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a21oi_1 _214_ (
    .A1(gout),
    .A2(_006_),
    .B1(din_enable),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a22o_1 _215_ (
    .A1(din_enable),
    .A2(din[6]),
    .B1(_071_),
    .B2(_072_),
    .X(buswires[6])
  );
  sky130_fd_sc_hd__nor4b_1 _216_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[7]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a22oi_1 _217_ (
    .A1(r2[7]),
    .A2(_023_),
    .B1(_024_),
    .B2(r4[7]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a221oi_1 _218_ (
    .A1(r6[7]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[7]),
    .C1(_073_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a22oi_1 _219_ (
    .A1(r7[7]),
    .A2(_016_),
    .B1(_019_),
    .B2(r1[7]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _220_ (
    .A1(r5[7]),
    .A2(_018_),
    .B1(gout),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand4_1 _221_ (
    .A(_074_),
    .B(_075_),
    .C(_076_),
    .D(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21oi_1 _222_ (
    .A1(gout),
    .A2(_007_),
    .B1(din_enable),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a22o_1 _223_ (
    .A1(din_enable),
    .A2(din[7]),
    .B1(_078_),
    .B2(_079_),
    .X(buswires[7])
  );
  sky130_fd_sc_hd__nor4b_1 _224_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[8]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a22oi_1 _225_ (
    .A1(r5[8]),
    .A2(_018_),
    .B1(_023_),
    .B2(r2[8]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a221oi_1 _226_ (
    .A1(r6[8]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[8]),
    .C1(_080_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a22oi_1 _227_ (
    .A1(r7[8]),
    .A2(_016_),
    .B1(_019_),
    .B2(r1[8]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a21oi_1 _228_ (
    .A1(r4[8]),
    .A2(_024_),
    .B1(gout),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand4_1 _229_ (
    .A(_081_),
    .B(_082_),
    .C(_083_),
    .D(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21oi_1 _230_ (
    .A1(gout),
    .A2(_008_),
    .B1(din_enable),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a22o_1 _231_ (
    .A1(din_enable),
    .A2(din[8]),
    .B1(_085_),
    .B2(_086_),
    .X(buswires[8])
  );
  sky130_fd_sc_hd__nor4bb_1 _232_ (
    .A(rout[1]),
    .B(rout[2]),
    .C_N(r1[9]),
    .D_N(rout[0]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a22oi_1 _233_ (
    .A1(r5[9]),
    .A2(_018_),
    .B1(_021_),
    .B2(r0[9]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__a221oi_1 _234_ (
    .A1(r6[9]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[9]),
    .C1(_087_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a22oi_1 _235_ (
    .A1(r2[9]),
    .A2(_023_),
    .B1(_024_),
    .B2(r4[9]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(r7[9]),
    .A2(_016_),
    .B1(gout),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _237_ (
    .A(_088_),
    .B(_089_),
    .C(_090_),
    .D(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _238_ (
    .A1(gout),
    .A2(_009_),
    .B1(din_enable),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a22o_1 _239_ (
    .A1(din_enable),
    .A2(din[9]),
    .B1(_092_),
    .B2(_093_),
    .X(buswires[9])
  );
  sky130_fd_sc_hd__and4b_1 _240_ (
    .A_N(rout[1]),
    .B(rout[2]),
    .C(r5[10]),
    .D(rout[0]),
    .X(_094_)
  );
  sky130_fd_sc_hd__a22oi_1 _241_ (
    .A1(r1[10]),
    .A2(_019_),
    .B1(_021_),
    .B2(r0[10]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a221oi_1 _242_ (
    .A1(r6[10]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[10]),
    .C1(_094_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a22oi_1 _243_ (
    .A1(r7[10]),
    .A2(_016_),
    .B1(_024_),
    .B2(r4[10]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _244_ (
    .A1(r2[10]),
    .A2(_023_),
    .B1(gout),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand4_1 _245_ (
    .A(_095_),
    .B(_096_),
    .C(_097_),
    .D(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21oi_1 _246_ (
    .A1(gout),
    .A2(_010_),
    .B1(din_enable),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a22o_1 _247_ (
    .A1(din_enable),
    .A2(din[10]),
    .B1(_099_),
    .B2(_100_),
    .X(buswires[10])
  );
  sky130_fd_sc_hd__and4b_1 _248_ (
    .A_N(rout[1]),
    .B(rout[2]),
    .C(r5[11]),
    .D(rout[0]),
    .X(_101_)
  );
  sky130_fd_sc_hd__a22oi_1 _249_ (
    .A1(r7[11]),
    .A2(_016_),
    .B1(_023_),
    .B2(r2[11]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a221oi_1 _250_ (
    .A1(r6[11]),
    .A2(_017_),
    .B1(_019_),
    .B2(r1[11]),
    .C1(_101_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a22oi_1 _251_ (
    .A1(r3[11]),
    .A2(_020_),
    .B1(_021_),
    .B2(r0[11]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _252_ (
    .A1(r4[11]),
    .A2(_024_),
    .B1(gout),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand4_1 _253_ (
    .A(_102_),
    .B(_103_),
    .C(_104_),
    .D(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(gout),
    .A2(_011_),
    .B1(din_enable),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a22o_1 _255_ (
    .A1(din_enable),
    .A2(din[11]),
    .B1(_106_),
    .B2(_107_),
    .X(buswires[11])
  );
  sky130_fd_sc_hd__nor4bb_1 _256_ (
    .A(rout[1]),
    .B(rout[2]),
    .C_N(r1[12]),
    .D_N(rout[0]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a22oi_1 _257_ (
    .A1(r0[12]),
    .A2(_021_),
    .B1(_024_),
    .B2(r4[12]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a221oi_1 _258_ (
    .A1(r3[12]),
    .A2(_020_),
    .B1(_023_),
    .B2(r2[12]),
    .C1(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a22oi_1 _259_ (
    .A1(r6[12]),
    .A2(_017_),
    .B1(_018_),
    .B2(r5[12]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a21oi_1 _260_ (
    .A1(r7[12]),
    .A2(_016_),
    .B1(gout),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand4_1 _261_ (
    .A(_109_),
    .B(_110_),
    .C(_111_),
    .D(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a21oi_1 _262_ (
    .A1(gout),
    .A2(_012_),
    .B1(din_enable),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a22o_1 _263_ (
    .A1(din_enable),
    .A2(din[12]),
    .B1(_113_),
    .B2(_114_),
    .X(buswires[12])
  );
  sky130_fd_sc_hd__and4b_1 _264_ (
    .A_N(rout[1]),
    .B(rout[2]),
    .C(r5[13]),
    .D(rout[0]),
    .X(_115_)
  );
  sky130_fd_sc_hd__a22oi_1 _265_ (
    .A1(r7[13]),
    .A2(_016_),
    .B1(_023_),
    .B2(r2[13]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a221oi_1 _266_ (
    .A1(r6[13]),
    .A2(_017_),
    .B1(_019_),
    .B2(r1[13]),
    .C1(_115_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a22oi_1 _267_ (
    .A1(r3[13]),
    .A2(_020_),
    .B1(_021_),
    .B2(r0[13]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _268_ (
    .A1(r4[13]),
    .A2(_024_),
    .B1(gout),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand4_1 _269_ (
    .A(_116_),
    .B(_117_),
    .C(_118_),
    .D(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _270_ (
    .A1(gout),
    .A2(_013_),
    .B1(din_enable),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22o_1 _271_ (
    .A1(din_enable),
    .A2(din[13]),
    .B1(_120_),
    .B2(_121_),
    .X(buswires[13])
  );
  sky130_fd_sc_hd__nor4b_1 _272_ (
    .A(rout[0]),
    .B(rout[1]),
    .C(rout[2]),
    .D_N(r0[14]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a22oi_1 _273_ (
    .A1(r2[14]),
    .A2(_023_),
    .B1(_024_),
    .B2(r4[14]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a221oi_1 _274_ (
    .A1(r6[14]),
    .A2(_017_),
    .B1(_020_),
    .B2(r3[14]),
    .C1(_122_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a22oi_1 _275_ (
    .A1(r7[14]),
    .A2(_016_),
    .B1(_019_),
    .B2(r1[14]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _276_ (
    .A1(r5[14]),
    .A2(_018_),
    .B1(gout),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand4_1 _277_ (
    .A(_123_),
    .B(_124_),
    .C(_125_),
    .D(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(gout),
    .A2(_014_),
    .B1(din_enable),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a22o_1 _279_ (
    .A1(din_enable),
    .A2(din[14]),
    .B1(_127_),
    .B2(_128_),
    .X(buswires[14])
  );
  sky130_fd_sc_hd__nor4bb_1 _280_ (
    .A(rout[1]),
    .B(rout[2]),
    .C_N(r1[15]),
    .D_N(rout[0]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a22oi_1 _281_ (
    .A1(r0[15]),
    .A2(_021_),
    .B1(_024_),
    .B2(r4[15]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a221oi_1 _282_ (
    .A1(r3[15]),
    .A2(_020_),
    .B1(_023_),
    .B2(r2[15]),
    .C1(_129_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a22oi_1 _283_ (
    .A1(r6[15]),
    .A2(_017_),
    .B1(_018_),
    .B2(r5[15]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(r7[15]),
    .A2(_016_),
    .B1(gout),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand4_1 _285_ (
    .A(_130_),
    .B(_131_),
    .C(_132_),
    .D(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(gout),
    .A2(_015_),
    .B1(din_enable),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a22o_1 _287_ (
    .A1(din_enable),
    .A2(din[15]),
    .B1(_134_),
    .B2(_135_),
    .X(buswires[15])
  );
  assign buswires_reg = buswires;
endmodule

(* src = "CPU.v:3.1-23.10" *)
module register_16bit(clk, rin, buswires, Rout);
  (* src = "CPU.v:10.23-10.27" *)
  output [15:0] Rout;
  wire [15:0] Rout;
  (* src = "CPU.v:8.18-8.26" *)
  input [15:0] buswires;
  wire [15:0] buswires;
  (* src = "CPU.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "CPU.v:6.11-6.14" *)
  input rin;
  wire rin;
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _00_ (
    .CLK(clk),
    .D(buswires[0]),
    .DE(rin),
    .Q(Rout[0])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _01_ (
    .CLK(clk),
    .D(buswires[1]),
    .DE(rin),
    .Q(Rout[1])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _02_ (
    .CLK(clk),
    .D(buswires[2]),
    .DE(rin),
    .Q(Rout[2])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _03_ (
    .CLK(clk),
    .D(buswires[3]),
    .DE(rin),
    .Q(Rout[3])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _04_ (
    .CLK(clk),
    .D(buswires[4]),
    .DE(rin),
    .Q(Rout[4])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _05_ (
    .CLK(clk),
    .D(buswires[5]),
    .DE(rin),
    .Q(Rout[5])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _06_ (
    .CLK(clk),
    .D(buswires[6]),
    .DE(rin),
    .Q(Rout[6])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _07_ (
    .CLK(clk),
    .D(buswires[7]),
    .DE(rin),
    .Q(Rout[7])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _08_ (
    .CLK(clk),
    .D(buswires[8]),
    .DE(rin),
    .Q(Rout[8])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _09_ (
    .CLK(clk),
    .D(buswires[9]),
    .DE(rin),
    .Q(Rout[9])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _10_ (
    .CLK(clk),
    .D(buswires[10]),
    .DE(rin),
    .Q(Rout[10])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _11_ (
    .CLK(clk),
    .D(buswires[11]),
    .DE(rin),
    .Q(Rout[11])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _12_ (
    .CLK(clk),
    .D(buswires[12]),
    .DE(rin),
    .Q(Rout[12])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _13_ (
    .CLK(clk),
    .D(buswires[13]),
    .DE(rin),
    .Q(Rout[13])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _14_ (
    .CLK(clk),
    .D(buswires[14]),
    .DE(rin),
    .Q(Rout[14])
  );
  (* src = "CPU.v:13.5-21.8" *)
  sky130_fd_sc_hd__edfxtp_1 _15_ (
    .CLK(clk),
    .D(buswires[15]),
    .DE(rin),
    .Q(Rout[15])
  );
endmodule
