/* Generated by Yosys 0.48+5 (git sha1 4581f75b0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module IR(din, IRin, clk, IR_out);
  wire [8:0] _00_;
  output [8:0] IR_out;
  wire [8:0] IR_out;
  input IRin;
  wire IRin;
  input clk;
  wire clk;
  input [15:0] din;
  wire [15:0] din;
  sky130_fd_sc_hd__edfxtp_1 _01_ (
    .CLK(clk),
    .D(din[8]),
    .DE(IRin),
    .Q(_00_[8])
  );
  sky130_fd_sc_hd__edfxtp_1 _02_ (
    .CLK(clk),
    .D(din[7]),
    .DE(IRin),
    .Q(_00_[7])
  );
  sky130_fd_sc_hd__edfxtp_1 _03_ (
    .CLK(clk),
    .D(din[6]),
    .DE(IRin),
    .Q(_00_[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _04_ (
    .CLK(clk),
    .D(din[5]),
    .DE(IRin),
    .Q(_00_[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _05_ (
    .CLK(clk),
    .D(din[4]),
    .DE(IRin),
    .Q(_00_[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _06_ (
    .CLK(clk),
    .D(din[3]),
    .DE(IRin),
    .Q(_00_[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _07_ (
    .CLK(clk),
    .D(din[2]),
    .DE(IRin),
    .Q(_00_[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _08_ (
    .CLK(clk),
    .D(din[1]),
    .DE(IRin),
    .Q(_00_[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _09_ (
    .CLK(clk),
    .D(din[0]),
    .DE(IRin),
    .Q(_00_[0])
  );
  BUF_X2 _10_ (
    .A(_00_[0]),
    .Z(IR_out[0])
  );
  BUF_X2 _11_ (
    .A(_00_[1]),
    .Z(IR_out[1])
  );
  BUF_X2 _12_ (
    .A(_00_[2]),
    .Z(IR_out[2])
  );
  BUF_X2 _13_ (
    .A(_00_[3]),
    .Z(IR_out[3])
  );
  BUF_X2 _14_ (
    .A(_00_[4]),
    .Z(IR_out[4])
  );
  BUF_X2 _15_ (
    .A(_00_[5]),
    .Z(IR_out[5])
  );
  BUF_X2 _16_ (
    .A(_00_[6]),
    .Z(IR_out[6])
  );
  BUF_X2 _17_ (
    .A(_00_[7]),
    .Z(IR_out[7])
  );
  BUF_X2 _18_ (
    .A(_00_[8]),
    .Z(IR_out[8])
  );
endmodule
